package org.pegdown

import org.scalatest.testng.TestNGSuite

class ScalaCustomParserTest extends CustomParserTest with TestNGSuite
class ScalaMarkdown103Test extends Markdown103Test with TestNGSuite
class ScalaMarukuTest extends MarukuTest with TestNGSuite
class ScalaPathologicalHtmlTest extends PathologicalHtmlTest with TestNGSuite
class ScalaPegDownTest extends PegDownTest with TestNGSuite
class ScalaPhpMarkdownExtraTest extends PhpMarkdownExtraTest with TestNGSuite
class ScalaPhpMarkdownTest extends PhpMarkdownTest with TestNGSuite